### ISSUE TITLE
What does scale x and scale y mean on the extrude contours node?

### ISSUE THREAD

**Issue by sebmooreaz** [lightact/Lightact-UE4#1]
I understand that This node expects an Array of Vectors where each vector in the array represents [x,y,i] of a contour, where x is the x coordinate, y is the y coordinate and i is the index of a contour. But what are the x and y scale?

I am feeding to the extrude contours node an array of Vec3d: (the z is used for the index so it goes from 0 to the ...amount of the vert array. I am also setting the height to 10 but I always get a ue4 crash when I feed the vert array and tris array to a create mesh section.... Looking for help.. Thanks

This is an example of the array of verts I use=
x=100 y=200 z(i)=0
x=100 y=200 z(i)=1

**Comment by lightact** [comment]
Sorry, I just saw this. It might be best to refer to [LightAct Answerhub](https://answerhub.lightact.io/) for support questions:

hmm...extrude contours is an experimental feature that will be probably removed in the future. It should work with [Find Contours](https://lightact.io/docs/find-circles-and-contours/) node in LightAct.

What this node outputs is vertices with index of the contour this vertex belongs to. So the structure would look similar to this:
x=100 y=200 z(i)=0
x=120 y=210 z(i)=0
x=130 y=240 z(i)=0
x=130 y=210 z(i)=1
x=150 y=214 z(i)=1
x=160 y=213 z(i)=1
x=170 y=212 z(i)=1


I hope this helps.
